services:
  - type: web
    name: ukhorsesbr-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: RAPIDAPI_KEY
        sync: false
      - key: BOT_TOKEN
        sync: false
